name: ssh-test
on:
  pull_request:
    branchs: [dev]

jobs:
  ssh-connect:
    runs-on: ubuntu-latest
    steps:
    - name: execute remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SSH_HOST }}
        username: ${{ secrets.REMOTE_SSH_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          whoami
          docker start ansible-server